version: '3'
services:

  #PHP Service
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
      PHP_IDE_CONFIG: "serverName=docker"
    working_dir: /www
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ${PATH_CONF}/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ${PATH_CONF}/php/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      - ${PATH_BACK}:/www
      - phpsocket:/var/run
    networks:
      - kt-team-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${PATH_BACK}:/www
      - ${PATH_LOG}/nginx:/var/log/nginx/
      - ${PATH_CONF}/nginx/conf.d/${NGINX_CONF}:/etc/nginx/conf.d/default.conf
      - "phpsocket:/var/run"      
    networks:
      - kt-team-network

  db:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    working_dir: /www
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ${PATH_DB}/dump:/app/dump
      - ${PATH_DB}/db:/var/lib/postgresql/data
    networks:
      - kt-team-network

  rabbitmq:
    image: rabbitmq:3.11.7-management-alpine
    working_dir: /www
    hostname: rabbit-mq
    restart: always
    container_name: 'rabbit-mq'
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    networks:
      - kt-team-network

#  supervisor:
#    build: ./docker/supervisor
#    container_name: 'supervisor'
#    restart: unless-stopped
#    volumes:
#      - ${PATH_BACK}:/www
#      - ./docker/supervisor/supervisord.conf:/etc/supervisor/supervisord.conf
#      - ${PATH_LOG}/supervisor:/var/log/supervisor
#      - phpsocket:/var/run
#    working_dir: /www
#    command: ["supervisord", "-c", "/etc/supervisor/supervisord.conf"]
#    networks:
#      - kt-team-network

#Docker Networks
networks:
  kt-team-network:
    driver: bridge

volumes:
    phpsocket: